#!/usr/bin/env node

// https://cirosantilli.com/cirodown#build-sass

const fs = require('fs');
const path = require('path');

const sass = require('sass');

const cirodown_nodejs = require('cirodown/nodejs');
fs.mkdirSync(cirodown_nodejs.DIST_PATH, {recursive: true})
const scss_input = fs.readFileSync(path.join(
  __dirname, cirodown_nodejs.PACKAGE_SASS_BASENAME)).toString();
let result;
result = sass.renderSync({
  data: scss_input,
  outputStyle: 'compressed',
});
fs.writeFileSync(cirodown_nodejs.PACKAGE_OUT_CSS_EMBED_PATH, result.css);
