#!/usr/bin/env node

const fs = require('fs');
const util = require('util');

// https://stackoverflow.com/questions/44447847/enums-in-javascript-with-es6/49709701#49709701
const make_enum = function(arr) {
  let obj = {};
  for (let val of arr){
    obj[val] = Symbol(val);
  }
  return Object.freeze(obj);
}

const AstNode = class {
  /**
   * @param {String} type - plaintext or macro
   * @param {Object[String, Array[AstNode]|String} arguments
   *        If type is macro, the Object with child arguments.
   *        Otherwise, it ype is text, , the raw String.
   */
  constructor(macro_name, args, line, column) {
    this.macro_name = macro_name;
    this.args = args;
    this.line = line;
    this.column = column;
  }

  convert(options) {
    let macro = macros[this.macro_name];
    return macro.convert(this.args, options);
  }
}

const ErrorMessage = class {
  constructor(message, line, column) {
    this.message = message;
    this.line = line;
    this.column = column;
  }

  toString() {
    let ret = 'error: ';
    let had_line_or_col = false;
    if (this.line !== undefined) {
      ret += `line ${this.line} `;
      had_line_or_col = true;
    }
    if (this.column !== undefined) {
      ret += `column ${this.column} `;
      had_line_or_col = true;
    }
    if (had_line_or_col)
      ret += ': ';
    ret += this.message;
    return ret
  }
}

const TokenType = make_enum([
  'PLAINTEXT',
  'MACRO_NAME',
  'POSITIONAL_ARGUMENT_START',
  'POSITIONAL_ARGUMENT_END',
  'NAMED_ARGUMENT_START',
  'NAMED_ARGUMENT_END',
]);

const Token = class {
  /**
   * @param {String} type
   * @param {String} value - Default: undefined
   * @param {number} line
   * @param {number} column
   */
  constructor(type, line, column, value) {
    this.type = type;
    this.line = line;
    this.column = column;
    this.value = value;
  }

  toJSON() {
    return {
      type:   this.type.toString(),
      line:   this.line,
      column: this.column,
      value:  this.value
    }
  }
}

const Argument = class {
  /**
   * @param {String} name
   */
  constructor(options) {
    this.name = options.name;
  }
}

const Macro = class {
  /**
   * @param {String} name
   * @param {Array[Argument]} args
   * @param {Function} convert
   */
  constructor(name, args, convert) {
    this.name = name;
    this.args = args;
    this.convert = convert;
    this.name_to_arg = {};
    this.index_to_arg = {};
    let i = 0;
    for (const arg of args) {
      let name = arg.name;
      if (name in this.name_to_arg) {
        throw new Error('name already taken: ' + name);
      }
      this.name_to_arg[name] = arg;
      this.index_to_arg[i] = arg;
      i += 1;
    }
  }
}

const convert_arg = function(arg) {
  let converted_arg = '';
  for (const macro of arg) {
    converted_arg += macro.convert()
  }
  return converted_arg;
}

let macro_list = [
  new Macro(
    'p',
    [
      new Argument({
        name: 'content',
      }),
    ],
    function(args, options) {
      return `<p>${convert_arg(args.content)}</p>\n`
    }
  ),
  new Macro(
    'a',
    [
      new Argument({
        name: 'href',
      }),
      new Argument({
        name: 'content',
      }),
    ],
    function(args, options) {
      return `<a href="${convert_arg(args.href)}">${convert_arg(args.content)}</p>`
    }
  ),
  new Macro(
    'plaintext',
    [
      new Argument({
        name: 'content',
      }),
    ],
    function(args, options) {
      return args;
    }
  ),
  new Macro(
    'toplevel',
    [
      new Argument({
        name: 'content',
      }),
      new Argument({
        name: 'title',
      }),
    ],
    function(args, options) {
      if (!'title' in args) {
        if ('title' in options) {
          title = options['title'];
        } else {
          title = IN_OUTPUT_ERROR_PREFIX + 'missing title';
          if (!options.body_only) {
            report_error_noline('HTML requires a non-empty title');
            // TODO report error with exit status.
          }
        }
        args.title = new AstNode('plaintext', title);
      }
      let ret = '';
      if (!options.body_only) {
        ret += `<!doctype html>
<html lang=en>
<head>
<meta charset=utf-8>
<title>${convert_arg(args.title)}</title>
<body>
`
      }
      ret += convert_arg(args.content);
      if (!options.body_only) {
        ret += `</body>
</html>
`
      }
      return ret;
    }
  ),
]

// Macros indexed by their name.
let macros = {};
for (const macro of macro_list) {
  macros[macro.name] = macro;
}

const IN_OUTPUT_ERROR_PREFIX = 'CIRODOWN_ERROR: ';
const ESCAPE_CHAR = '\\';
const START_POSITIONAL_ARGUMENT_CHAR = '{';
const END_POSITIONAL_ARGUMENT_CHAR = '}';
const START_NAMED_ARGUMENT_CHAR = '[';
const END_NAMED_ARGUMENT_CHAR = ']';
const ESCAPABLE_CHARS = new Set([
  ESCAPE_CHAR,
  START_POSITIONAL_ARGUMENT_CHAR,
  END_POSITIONAL_ARGUMENT_CHAR,
  START_NAMED_ARGUMENT_CHAR,
  END_NAMED_ARGUMENT_CHAR,
]);

const char_is_alphanumeric = function(c) {
  let code = c.codePointAt(0);
  return (
    // 0-9
    (code > 47 && code < 58) ||
    // A-Z
    (code > 64 && code < 91) ||
    // a-z
    (code > 96 && code < 123)
  )
}

// Valid macro name characters.
const char_is_macro = function (c) {
  return char_is_alphanumeric(c) || c === '_';
};
char_is_macro.chars = new Set(['-', '_']);

const closing_token = function(token) {
  if (token === TokenType.POSITIONAL_ARGUMENT_START)
    return TokenType.POSITIONAL_ARGUMENT_END;
  if (token === TokenType.NAMED_ARGUMENT_START)
    return TokenType.NAMED_ARGUMENT_END;
  return undefined;
}

/**
 * @param {String} input_string
 * @returns {Array[Token]}
 */
const tokenize = function(input_string, extra_returns={}) {
  // https://stackoverflow.com/questions/21397316/split-javascript-string-into-array-of-codepoints-taking-into-account-surrogat/42596897#42596897
  let chars = Array.from(input_string);
  let tokens = [];
  let i = -1;
  let line = 1;
  let column = 1;
  let cur_c;
  // Holds a FIFO with the currenty ongoing arguments.
  // We must maintain this to know which argument is literal or not.
  let macro_argument_stack = [];
  // We are just after a previous argument, or just after the macro name.
  // Therefore the next char could be the start of a new argument.
  let last_possible_new_argument_index;
  let failed = false;
  extra_returns.errors = [];

  const error = function(message) {
    extra_returns.errors.push(new ErrorMessage(message, line, column));
  }

  const assert_could_be_argument = function() {
    if (i !== last_possible_new_argument_index) {
      error('cannot start a macro argument here. It has to come after a macro name or another macro argument.');
    }
  }

  // Advance the current character and set cur_c to the next one.
  //
  // Maintain the newline count up to date for debug messages.
  //
  // The current index must only be incremented through this function
  // and never directly.
  const consume = function() {
    if (chars[i] === '\n') {
      line += 1;
      column = 1;
    } else {
      column += 1;
    }
    i += 1;
    if (i >= chars.length) {
      return false;
    }
    cur_c = chars[i];
    return true;
  }

  const consume_optional_newline = function() {
    if (cur_c === '\n') {
      consume();
    }
  }

  const push_token = function(token, value) {
    tokens.push(new Token(token, line, column, value));
  }

  const tokenize_plaintext = function(tokens, c) {
    let last_token = tokens[tokens.length - 1];
    if (last_token.type === TokenType.PLAINTEXT) {
      last_token.value += c;
    } else {
      push_token(TokenType.PLAINTEXT, c);
    }
  }

  push_token(TokenType.MACRO_NAME, 'toplevel');
  push_token(TokenType.POSITIONAL_ARGUMENT_START);
  push_token(TokenType.MACRO_NAME, 'p');
  push_token(TokenType.POSITIONAL_ARGUMENT_START);
  while (consume()) {
    if (cur_c === '\\') {
      next_c = chars[i + 1];
      if (ESCAPABLE_CHARS.has(next_c)) {
        tokenize_plaintext(tokens, next_c);
        consume();
      } else {
        let macro_name = '';
        consume();
        while (char_is_macro(cur_c)) {
          macro_name += cur_c;
          consume();
        }
        consume_optional_newline();
        last_possible_new_argument_index = i;
        push_token(TokenType.MACRO_NAME, macro_name);
        macro_argument_stack.push([macros[macro_name], 0]);
      }
    } else if (cur_c === START_NAMED_ARGUMENT_CHAR) {
      assert_could_be_argument();
      consume_optional_newline();
    } else if (cur_c === END_NAMED_ARGUMENT_CHAR) {
      consume_optional_newline();
      last_possible_new_argument_index = i;
    } else if (cur_c === START_POSITIONAL_ARGUMENT_CHAR) {
      consume_optional_newline();
      push_token(TokenType.POSITIONAL_ARGUMENT_START);
    } else if (cur_c === END_POSITIONAL_ARGUMENT_CHAR) {
      consume_optional_newline();
      last_possible_new_argument_index = i;
      push_token(TokenType.POSITIONAL_ARGUMENT_END);
    } else if (cur_c === '\n') {
      if (((i + 1) === chars.length)) {
        // Do nothing.
      } else if (chars[i + 1] === '\n') {
        // Double newline.
        push_token(TokenType.POSITIONAL_ARGUMENT_END);
        push_token(TokenType.MACRO_NAME, 'p');
        push_token(TokenType.POSITIONAL_ARGUMENT_START);
        consume();
        done = true;
      } else {
        tokenize_plaintext(tokens, cur_c);
      }
    } else {
      tokenize_plaintext(tokens, cur_c);
    }
  }
  push_token(TokenType.POSITIONAL_ARGUMENT_END);
  push_token(TokenType.POSITIONAL_ARGUMENT_END);
  return tokens;
}

// Parse tokens into the AST tree.
const parse = function(tokens, options, extra_returns={}) {
  extra_returns.errors = [];
  let state = {
    extra_returns: extra_returns,
    i: 0,
    options: options,
    token: tokens[0],
    tokens: tokens,
  };
  let ast = parse_macro(state);
  if (state.i < tokens.length) {
    parse_report_error(state, `unexpected tokens at the end of input`);
  }
  return ast;
}

// Consume one token.
const parse_consume = function(state) {
  state.i += 1;
  if (state.i >= state.tokens.length)
    return undefined;
  state.token = state.tokens[state.i];
  parse_log_debug(state, 'function: consume');
  parse_log_debug(state, 'state.i = ' + state.i.toString())
  parse_log_debug(state, 'state.token = ' + JSON.stringify(state.token));
  parse_log_debug(state);
  return state.token;
}

const parse_log_debug = function(state, msg='') {
  if (state.options.show_parse) {
    console.log(msg);
  }
}

// Parse one macro.
const parse_macro = function(state) {
  parse_log_debug(state, 'function: parse_macro');
  parse_log_debug(state, 'state.i = ' + state.i.toString());
  parse_log_debug(state);
  if (state.token.type === TokenType.MACRO_NAME) {
    let macro_name = state.token.value;
    let macro_line = state.token.line;
    let macro_column = state.token.column;
    let macro = macros[macro_name];
    console.log(macro);
    let arg_count = 0;
    let args = {};
    // Consume the MACRO_NAME token out.
    parse_consume(state);
    while (
      state.token.type === TokenType.POSITIONAL_ARGUMENT_START ||
      state.token.type === TokenType.NAMED_ARGUMENT_START
    ) {
      let arg;
      if (state.token.type === TokenType.POSITIONAL_ARGUMENT_START) {
        console.log(macro);
        arg = macro.index_to_arg[arg_count];
      } else {
        console.log(state.token.type);
        asdf
        //arg = macro.index_to_arg[parse_consume(state)];
      }
      let open_type = state.token.type;
      let arg_children = [];
      // Consume the *_ARGUMENT_START token out.
      parse_consume(state);
      while (
        state.token.type !== TokenType.POSITIONAL_ARGUMENT_END &&
        state.token.type !== TokenType.NAMED_ARGUMENT_END
      ) {
        parse_log_debug(state, 'case: argument');
        parse_log_debug(state, state.token.type);
        parse_log_debug(state);
        // The recursive case.
        arg_children.push(parse_macro(state));
      }
      if (state.token.type !== closing_token(open_type)) {
        parse_report_error(state,
          `expected a closing ${END_POSITIONAL_ARGUMENT_CHAR} found ${state.token.type.toString()}`);
      }
      args[arg.name] = arg_children;
      arg_count += 1;
      // Consume the *_ARGUMENT_END token out.
      parse_consume(state);
    }
    return new AstNode(macro_name, args, macro_line, macro_column);
  } else if (state.token.type === TokenType.PLAINTEXT) {
    // Non-recursive case.
    let plaintext_node = new AstNode(
      'plaintext',
      state.token.value,
      state.token.line,
      state.token.column
    );
    // Consume the PLAINTEXT node out.
    parse_consume(state);
    return plaintext_node;
  } else {
    parse_report_error(
      state,
      `unexpected token ${state.token.type.toString()}`
    );
    let node = new AstNode(
      'plaintext',
      IN_OUTPUT_ERROR_PREFIX + 'unexpected token',
      state.token.line,
      state.token.column
    );
    // Consume past whatever happened to avoid an infinite loop.
    consume();
    return node;
  }
  state.i += 1;
}

const parse_report_error = function(state, message) {
  state.extra_returns.errors.push(new ErrorMessage(
    message, state.token.line, state.token.column));
}

/**
 * Main cirodown input to HTML/LaTeX/etc. output API wrapper.
 *
 * @returns {String}
 */
const convert = function(
  input_string,
  options,
  extra_returns={},
) {
  if (options === undefined) {
    options = {};
  }
  if (!'body_only'   in options) { options.body_only   = false; }
  if (!'show_parse'  in options) { options.show_parse  = false; }
  if (!'show_tokens' in options) { options.show_tokens = false; }
  extra_returns.errors = [];
  let sub_extra_returns;
  sub_extra_returns = {};
  let tokens = tokenize(input_string, sub_extra_returns);
  extra_returns.tokens = tokens;
  extra_returns.errors.push(...sub_extra_returns.errors);
  sub_extra_returns = {};
  let ast = parse(tokens, options, sub_extra_returns);
  extra_returns.ast = ast;
  extra_returns.errors.push(...sub_extra_returns.errors);
  return ast.convert(options);
}

exports.convert = convert;

if (require.main === module) {
  let input;
  const encoding = 'utf8';
  let title;
  if (process.argv.length > 2) {
    title = process.argv[2]
    input = fs.readFileSync(title, encoding);
  } else {
    title = 'stdin'
    input = fs.readFileSync(0, encoding);
  }
  let extra_returns = {};
  let output = convert(
    input,
    {
      body_only: true,
      title: title,
      //show_parse: true,
    },
    extra_returns
  );
  console.log(output);
  if (true) {
    console.error('tokens:');
    console.error(JSON.stringify(extra_returns.tokens, null, 2));
    console.error();
  }
  if (true) {
    console.error('ast:');
    console.error(JSON.stringify(extra_returns.ast, null, 2));
    console.error();
  }
  for (const error of extra_returns.errors) {
    console.error(error.toString());
  }
  process.exit(extra_returns.errors.length > 0);
}
