#!/usr/bin/env node

const child_process = require('child_process');
const fs = require('fs');
const path = require('path');
const { PerformanceObserver, performance } = require('perf_hooks');

const better_sqlite3 = require('better-sqlite3');
const chokidar = require('chokidar');
// This library is terrible, too much magic, hard to understand interface,
// does not do some obvious basics.
const commander = require('commander');
const git_url_parse = require("git-url-parse");
const is_installed_globally = require('is-installed-globally');
const sass = require('sass');

const cirodown = require('cirodown');
const cirodown_nodejs = require('cirodown/nodejs');

const CIRODOWN_EXT = '.ciro';
const CIRODOWN_JSON = 'cirodown.json';
const HTML_EXT = '.html';
const SASS_EXT = '.scss';
const TMP_DIRNAME = 'out';
const DEFAULT_IGNORE_BASENAMES = [
  '.git',
  '.gitignore',
  '.sass-cache',
  'main.liquid.html',
  'node_modules',
  'package-lock.json',
  'package.json',
  TMP_DIRNAME,
  cirodown_nodejs.PACKAGE_SASS_BASENAME,
];
const DEFAULT_IGNORE_BASENAMES_SET = new Set(DEFAULT_IGNORE_BASENAMES);
const ENCODING = 'utf8';
// https://cirosantilli.com/cirodown#index-files
const INDEX_FILE_BASENAMES_NOEXT = new Set([
  'README',
  'index',
]);
const IO_RENAME_MAP = {};
for (let i of INDEX_FILE_BASENAMES_NOEXT) {
  IO_RENAME_MAP[i] = 'index';
}

class SqliteIdProvider extends cirodown.IdProvider {
  constructor(convert_input_options) {
    super();
    this.delete_ids_stmt = convert_input_options.db.prepare(
      `DELETE FROM '${convert_input_options.ids_table_name}' WHERE path = ?`);
    this.delete_includes_stmt = convert_input_options.db.prepare(
      `DELETE FROM '${convert_input_options.includes_table_name}' WHERE from_path = ?`);
    this.get_id_stmt = convert_input_options.db.prepare(
      `SELECT path,ast_json FROM ${convert_input_options.ids_table_name} WHERE id = ?`);
    this.get_includes_stmt = convert_input_options.db.prepare(
      `SELECT from_id FROM ${convert_input_options.includes_table_name} WHERE to_id = ?`);
  }

  clear(input_path_noext_renamed) {
    this.delete_ids_stmt.run(input_path_noext_renamed);
    this.delete_includes_stmt.run(input_path_noext_renamed);
  }

  get_noscope(id, context) {
    let get_ret = this.get_id_stmt.get(id);
    if (get_ret === undefined) {
      return undefined;
    } else {
      const ast = cirodown.AstNode.fromJSON(get_ret.ast_json);
      ast.input_path = get_ret.path;
      ast.id = id;
      if (context !== undefined) {
        cirodown.validate_ast(ast, context);
      }
      return ast;
    }
  }

  get_includes(to_id, context) {
    let all_rets = this.get_includes_stmt.all(to_id);
    let ret = [];
    for (const all_ret of all_rets) {
      const from_ast = this.get(all_ret.from_id, context);
      if (from_ast === undefined) {
        throw 'parent ID of include not in database, not sure how this can happen so throwing';
      } else {
        ret.push(from_ast);
      }
    }
    return ret;
  }

}

class SqliteFileProvider extends cirodown.FileProvider {
  constructor(convert_input_options) {
    super();
    this.get_file_stmt = convert_input_options.db.prepare(
      `SELECT * FROM ${convert_input_options.files_table_name} WHERE path = ?`);
  }

  get(path) {
    let get_ret = this.get_file_stmt.get(path);
    if (get_ret === undefined) {
      return undefined;
    } else {
      return get_ret;
    }
  }
}

/** Report an error with the CLI usage and exit in error. */
function cli_error(message) {
  console.error(`error: ${message}`);
  process.exit(1);
}

function cmd_get_stdout(cmd, args=[], options={}) {
  if (!('dry_run' in options)) {
    options.dry_run = false;
  }
  if (!('show_cmd' in options)) {
    options.show_cmd = true;
  }
  let out;
  const cmd_str = ([cmd].concat(args)).join(' ');
  if (options.show_cmd) {
    console.log(cmd_str);
  }
  if (!options.dry_run) {
    out = child_process.spawnSync(cmd, args);
  }
  let ret;
  if (options.dry_run) {
    ret = '';
  } else {
    if (out.status != 0 && options.throw_on_error) {
      let msg = `cmd: \n${cmd_str}\n`;
      if (out.stdout !== null) {
        msg += `stdout: \n${out.stdout.toString(ENCODING)}\n`;
      }
      if (out.stderr !== null) {
        msg += `stdout: \n${out.stdout.toString(ENCODING)}\n`;
      }
      throw msg;
    }
    ret = out.stdout.toString(ENCODING);
  }
  return ret;
}

function convert_files_in_directory(input_path, options, convert_input_options) {
  for (const one_path of walk_files_recursively(input_path, DEFAULT_IGNORE_BASENAMES_SET)) {
    convert_path_to_file(input_path, path.relative(input_path, one_path), options, convert_input_options);
  }
}

/** Extract IDs from all input files into the ID database, without fully converting. */
function convert_files_in_directory_extract_ids(input_path, options, convert_input_options) {
  convert_files_in_directory(
    input_path,
    cirodown.clone_and_set(options, 'render', false),
    convert_input_options
  );
}

/** Convert input from a string to output and return the output as a string.
 *
 * Wraps cirodown.convert with CLI usage convenience.
 *
 * @param {String} input
 * @param {Object} options - options to be passed to cirodown.convert
 * @param {Object} convert_input_options - control options for this function,
 *                 not passed to cirodown.convert. Also contains some returns:
 *                 - {bool} had_error
 *                 - {Object} extra_returns
 * @return {String}
 */
function convert_input(input, options, convert_input_options={}) {
  const new_options = Object.assign({}, options);
  if ('input_path_noext_renamed' in convert_input_options) {
    new_options.input_path = convert_input_options.input_path_noext_renamed;
  }
  if ('db' in convert_input_options) {
    new_options.id_provider = new SqliteIdProvider(convert_input_options);
    new_options.file_provider = new SqliteFileProvider(convert_input_options);
  }
  if ('title' in convert_input_options) {
    new_options.title = convert_input_options.title;
  }
  new_options.extra_returns = {};
  // If we don't where the output will go (the case for stdout) or
  // the user did not explicitly request full embedding, inline all CSS.
  // Otherwise, include and external CSS to make each page lighter.
  if (convert_input_options.commander.htmlEmbed) {
    new_options.template_vars.style = fs.readFileSync(cirodown_nodejs.PACKAGE_OUT_CSS_EMBED_PATH, ENCODING);
    let scripts_str = '';
    for (const script_path of cirodown_nodejs.JS_LOCAL_INCLUDES) {
      scripts_str += `<script>${fs.readFileSync(script_path)}</script>\n`
    }
    scripts_str += `<script>${fs.readFileSync(cirodown_nodejs.PACKAGE_OUT_JS_LOCAL_PATH, ENCODING)}</script>\n`;
    new_options.template_vars.post_body = scripts_str;
  } else {
    let includes_str = ``;
    let scripts_str = ``;

    let includes = [];
    let scripts = [];

    if (convert_input_options.external_css_and_js) {
      scripts.push(
        'https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js',
        'https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/sorts/tablesort.date.min.js',
        'https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/sorts/tablesort.dotsep.min.js',
        'https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/sorts/tablesort.filesize.min.js',
        'https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/sorts/tablesort.monthname.min.js',
        'https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/sorts/tablesort.number.min.js',
      );
    }

    let includes_local = [];
    let scripts_local = [];

    if (!convert_input_options.external_css_and_js) {
      includes_local.push(...cirodown_nodejs.CSS_LOCAL_INCLUDES);
      scripts_local.push(...cirodown_nodejs.JS_LOCAL_INCLUDES);
    }

    includes_local.push(convert_input_options.out_css_path);
    scripts_local.push(convert_input_options.out_js_path);

    if (
      convert_input_options.output_path !== undefined &&
      !is_installed_globally
    ) {
      for (const include of includes_local) {
        includes.push(path.relative(path.dirname(convert_input_options.output_path), include));
      }
      for (const script of scripts_local) {
        scripts.push(path.relative(path.dirname(convert_input_options.output_path), script));
      }
    } else {
      includes.push(...includes_local);
      scripts.push(...scripts_local);
    }

    for (const include of includes) {
      includes_str += `@import "${include}";\n`;
    }
    for (const script of scripts) {
      scripts_str += `<script src="${script}"></script>\n`;
    }

    new_options.template_vars.style = `\n${includes_str}`;
    new_options.template_vars.post_body = `${scripts_str}`;
  }
  // Finally, do the conversion!
  const output = cirodown.convert(input, new_options, new_options.extra_returns);
  if (convert_input_options.commander.showTokens) {
    console.error('tokens:');
    console.error(JSON.stringify(new_options.extra_returns.tokens, null, 2));
    console.error();
  }
  if (convert_input_options.commander.showAst) {
    console.error('ast:');
    console.error(JSON.stringify(new_options.extra_returns.ast, null, 2));
    console.error();
  }
  if (convert_input_options.commander.debugPerf) {
    console.error(`perf start: ${new_options.extra_returns.debug_perf.start}`);
    console.error(`perf tokenize_pre: ${new_options.extra_returns.debug_perf.tokenize_pre}`);
    console.error(`perf tokenize_post: ${new_options.extra_returns.debug_perf.tokenize_post}`);
    console.error(`perf parse_start: ${new_options.extra_returns.debug_perf.parse_start}`);
    console.error(`perf post_process_start: ${new_options.extra_returns.debug_perf.post_process_start}`);
    console.error(`perf post_process_end: ${new_options.extra_returns.debug_perf.post_process_end}`);
    console.error(`perf render_pre: ${new_options.extra_returns.debug_perf.render_pre}`);
    console.error(`perf render_post: ${new_options.extra_returns.debug_perf.render_post}`);
    console.error(`perf end: ${new_options.extra_returns.debug_perf.end}`);
  }
  for (const error of new_options.extra_returns.errors) {
    console.error(error.toString(convert_input_options.input_path));
  }
  convert_input_options.extra_returns = new_options.extra_returns;
  if (new_options.extra_returns.errors.length > 0) {
    convert_input_options.had_error = true;
  }
  if (convert_input_options.commander.debugPerf) {
    console.error(`perf convert_input_end ${performance.now()}`);
  }
  return output;
}

/** Convert filetypes that cirodown knows how to convert, and just copy those that we don't, e.g.:
 *
 * * .ciro to .html
 * * .scss to .css
 *
 * @param {string} input_path - path relative to the base_path
 *
 * The output file name is derived from the input file name with the output extension.
 */
function convert_path_to_file(base_path, input_path, options, convert_input_options={}) {
  let input_path_parse = path.parse(input_path);
  let output_name = input_path_parse.name;
  if (input_path_parse.ext === CIRODOWN_EXT && output_name in IO_RENAME_MAP) {
    output_name = IO_RENAME_MAP[output_name];
  }
  let output_path_noext = path.join(input_path_parse.dir, output_name);
  if (convert_input_options.output_path === undefined) {
    if (convert_input_options.outdir) {
      output_path_noext = path.join(convert_input_options.outdir, output_path_noext);
    }
  } else {
    output_path_noext = convert_input_options.output_path;
  }
  fs.mkdirSync(path.dirname(output_path_noext), {recursive: true});
  if (input_path_parse.ext === CIRODOWN_EXT) {
    let message_prefix;
    if (options.render) {
      message_prefix = 'convert';
    } else {
      message_prefix = 'extract_ids';
    }
    let message = `${message_prefix} ${input_path}`;
    console.log(message);
    const output_path = output_path_noext + '.' + options.output_format;
    const new_convert_input_options = Object.assign({}, convert_input_options);
    new_convert_input_options.output_path = output_path;
    let t0 = performance.now();
    let output = convert_path(base_path, input_path, options, new_convert_input_options);
    let t1 = performance.now();
    console.log(`${message} finished in ${t1 - t0} ms`);

    fs.writeFileSync(output_path, output);
  } else {
    if (options.render) {
      if (input_path_parse.ext === SASS_EXT) {
        console.log(`sass ${input_path}`);
        fs.writeFileSync(
          output_path_noext + '.css',
          sass.renderSync({
            data: fs.readFileSync(input_path, convert_input_options.encoding),
            outputStyle: 'compressed',
          }).css
        );
      } else {
        // Otherwise, just copy the file over if needed.
        const output_path = output_path_noext + input_path_parse.ext;
        if (output_path !== input_path) {
          console.log(`copy ${input_path}`);
          fs.copyFileSync(input_path, output_path);
        }
      }
    }
  }
  if (convert_input_options.commander.debugPerf) {
    console.error(`perf convert_path_to_file_end ${performance.now()}`);
  }
}

/** Convert cirodown input from a path to string output and return the output as a string.
 *
 * @return {String}
 */
function convert_path(base_path, input_path, options, convert_input_options) {
  let full_path = path.join(base_path, input_path);
  let new_options = Object.assign({}, options);
  let new_convert_input_options = Object.assign({}, convert_input_options);
  let input = fs.readFileSync(full_path, new_convert_input_options.encoding);
  let input_path_parse = path.parse(input_path);
  let input_path_basename_noext = input_path_parse.name;

  let toplevel_id;
  if (INDEX_FILE_BASENAMES_NOEXT.has(input_path_basename_noext)) {
    if (fs.existsSync(path.join(input_path_parse.dir, CIRODOWN_JSON))) {
      // https://cirosantilli.com/cirodown#the-toplevel-index-file
      toplevel_id = undefined;
    } else {
      // https://cirosantilli.com/cirodown#the-id-of-the-first-header-is-derived-from-the-filename
      toplevel_id = path.basename(path.dirname(path.resolve(input_path)));
    }
  } else {
    toplevel_id = input_path_basename_noext;
  }
  new_options.toplevel_id = toplevel_id;
  let input_path_basename_noext_renamed = get_renamed_basename(input_path_basename_noext);
  let input_path_noext_renamed = path.join(input_path_parse.dir, input_path_basename_noext_renamed);
  new_convert_input_options.input_path_noext_renamed = input_path_noext_renamed;
  let output = convert_input(input, new_options, new_convert_input_options);
  const context = new_convert_input_options.extra_returns.context;
  if (convert_input_options.commander.showHeaders) {
    console.error(context.header_graph.toString());
  }

  // Update the Sqlite databse with results from the conversion.
  if (convert_input_options.commander.debugPerf) {
    console.error(`perf convert_path_pre_sqlite ${performance.now()}`);
  }
  if ('db' in convert_input_options) {
    const ids = new_convert_input_options.extra_returns.ids;
    const insert_id_stmt = convert_input_options.db.prepare(
      `INSERT INTO '${convert_input_options.ids_table_name}'
      (id, path, ast_json) VALUES (?, ?, ?);`
    );
    const insert_include_stmt = convert_input_options.db.prepare(
      `INSERT INTO '${convert_input_options.includes_table_name}'
      (from_id, from_path, to_id) VALUES (?, ?, ?);`
    );
    const insert_file_stmt = convert_input_options.db.prepare(
      `INSERT OR REPLACE INTO '${convert_input_options.files_table_name}' ` +
      `(path, toplevel_scope_cut_length, toplevel_id) VALUES (?, ?, ?);`
    );
    if (convert_input_options.commander.debugPerf) {
      console.error(`perf convert_path_pre_sqlite_transaction ${performance.now()}`);
    }
    // This was the 80% bottleneck at Cirodown f8fc9eacfa794b95c1d9982a04b62603e6d0bb83
    // before being converted to a single transaction!
    convert_input_options.db.transaction(() => {
      for (const id in ids) {
        const ast = ids[id];
        insert_id_stmt.run(id, ast.input_path, JSON.stringify(ast));
      }
      for (const header_ast of context.headers_with_include) {
        for (const include of header_ast.includes) {
          insert_include_stmt.run(header_ast.id, header_ast.input_path, include);
        }
      }
      insert_file_stmt.run(
        input_path_noext_renamed,
        context.toplevel_scope_cut_length,
        context.toplevel_id
      );
    })();
    if (convert_input_options.commander.debugPerf) {
      console.error(`perf convert_path_post_sqlite_transaction ${performance.now()}`);
    }
  }

  if (new_convert_input_options.had_error) {
    convert_input_options.had_error = true;
  }
  if (convert_input_options.commander.debugPerf) {
    console.error(`perf convert_path_end ${performance.now()}`);
  }
  return output;
}

function generate_redirects(convert_input_options, cirodown_json, html_x_extension, outdir) {
  const id_provider = new SqliteIdProvider(convert_input_options);
  for (let redirect_src_id in cirodown_json.redirects) {
    const redirect_target_id = cirodown_json.redirects[redirect_src_id];
    const target_id_ast = id_provider.get(redirect_target_id)
    if (target_id_ast === undefined) {
      cli_error(`redirection target ID "${redirect_target_id}" not found`);
    }
    const redirect_href = cirodown.x_href(
      target_id_ast,
      {
        // This will need changing when we do:
        // https://github.com/cirosantilli/cirodown/issues/44
        // The simple solution is to just make all redirects point
        // to the index in that case.
        include_path_set: new Set(),
        options: {
          file_provider: new cirodown_nodejs.ZeroFileProvider(),
          input_path: redirect_src_id,
          html_x_extension: html_x_extension,
        }
      }
    );
    // https://stackoverflow.com/questions/10178304/what-is-the-best-approach-for-redirection-of-old-pages-in-jekyll-and-github-page/36848440#36848440
    fs.writeFileSync(path.join(outdir, redirect_src_id + HTML_EXT),
`<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Redirecting...</title>
<link rel="canonical" href="${redirect_href}"/>
<meta http-equiv="refresh" content="0;url=${redirect_href}" />
</head>
<body>
<h1>Redirecting...</h1>
<a href="${redirect_href}">Click here if you are not redirected.<a>
<script>location='${redirect_href}'</script>
</body>
</html>
`);
  }
}

function get_renamed_basename(original) {
  if (original in IO_RENAME_MAP) {
    return IO_RENAME_MAP[original];
  } else {
    return original;
  }
}

/**
 * @return {String} full Git SHA of the source.
 */
function git_sha(input_path, src_branch) {
  const args = ['-C', input_path, 'log', '-n1', '--pretty=%H'];
  if (src_branch !== undefined) {
    args.push(src_branch);
  }
  return cmd_get_stdout('git', args, {show_cmd: false, throw_on_error: true}).slice(0, -1);
}

/** https://stackoverflow.com/questions/5827612/node-js-fs-readdir-recursive-directory-search
 *
 * @param {Set} skip_basenames
 */
function* walk_files_recursively(file_or_dir, skip_basenames) {
  if (fs.lstatSync(file_or_dir).isDirectory()) {
    const dirents = fs.readdirSync(file_or_dir, {withFileTypes: true});
    for (const dirent of dirents) {
      if (!skip_basenames.has(dirent.name)) {
        const res = path.join(file_or_dir, dirent.name);
        if (dirent.isDirectory()) {
          yield* walk_files_recursively(res, skip_basenames);
        } else {
          yield res;
        }
      }
    }
  } else {
    yield file_or_dir;
  }
}

// CLI options.
commander.option('--body-only', 'output only the content inside the HTLM body element', false);
commander.option('--debug-perf', 'https://cirosantilli.com/linux-kernel-module-cheat#debug-perf', false);
commander.option('--dry-run', "don't run most external commands, see: https://github.com/cirosantilli/linux-kernel-module-cheat/tree/6d0a900f4c3c15e65d850f9d29d63315a6f976bf#dry-run-to-get-commands-for-your-project", false);
commander.option('--generate', 'http://cirosantilli.com/cirodown#generate', false);
commander.option('--generate-redirects', 'http://cirosantilli.com/cirodown#redirects', false);
commander.option('--generate-multifile', 'http://cirosantilli.com/cirodown#generate-multifile', false);
commander.option('--help-macros', 'print the metadata of all macros to stdout in JSON format. https://cirosantilli.com/cirodown/#', false);
commander.option('--html-embed', 'http://cirosantilli.com/cirodown#html-embed', false);
commander.option('--html-single-page', 'http://cirosantilli.com/cirodown#html-single-page', false);
commander.option('--no-html-x-extension', 'http://cirosantilli.com/cirodown#no-html-x-extension');
commander.option('--no-db', 'ignore the ID database, mostly for testing https://cirosantilli.com/cirosantilli#internal-cross-file-references-internals');
commander.option('--outdir <outdir>', 'if the output would be saved to a file e.g. when building a directory, use this directory as the root');
commander.option('-o, --outfile <outfile>', 'http://cirosantilli.com/cirodown#outfile');
commander.option('-O, --output-format <output-format>', 'https://cirosantilli.com/cirodown#output-format', 'html');
commander.option('-p --publish', 'http://cirosantilli.com/cirodown#publish', false);
commander.option('-P, --publish-commit <commit-message>', 'http://cirosantilli.com/cirodown#publish-commit');
commander.option('--show-ast', 'print the AST to stderr', false);
commander.option(
  '--show-ast-inside',
  'print the AST to stderr from inside convert before it returns. ' +
    'Useful to debug the program if conversion blow up on the next stages.',
  false
);
commander.option('--show-headers', 'https://cirosantilli.com/cirodown#show-headers', false);
commander.option('--show-parse', 'print parsing internals to stderr', false);
commander.option('--show-tokenize', 'print tokenization internals to stderr', false);
commander.option('--show-tokens', 'print the token stream to stderr', false);
commander.option(
  '--show-tokens-inside',
  'print the token stream to stderr from inside convert before it returns. ' +
    'Useful to debug the program if conversion blow up on the next stages. ' +
    'Also adds token index to the output, which makes debugging the parser ' +
    'way easier.',
  false
);
commander.option('--stdout', 'print output to stdout instead of saving to a file', false);
commander.option('--template <template>', 'http://cirosantilli.com/cirodown#template');
commander.option('-w, --watch', 'http://cirosantilli.com/cirodown#watch', false);
commander.option('--xss-unsafe', 'https://cirosantilli.com/cirodown#xss-unsafe');
let inputPath;
commander.arguments(
  '[input_path]',
  undefined,
  'http://cirosantilli.com/cirodown#cirodown-executable',
).action(function (input_path) {
  inputPath = input_path;
});
commander.parse(process.argv);

// Action.
if (commander.helpMacros) {
  console.log(JSON.stringify(cirodown.macro_list(), null, 2));
} else {
  let input;
  let title;
  let output;
  let publish = commander.publish || commander.publishCommit !== undefined;
  let html_x_extension;
  let cirodown_json = {};
  let input_dir;
  if (inputPath === undefined) {
    if (publish || commander.watch) {
      inputPath = '.';
    }
  }
  if (inputPath !== undefined && fs.existsSync(CIRODOWN_JSON)) {
    Object.assign(cirodown_json, JSON.parse(fs.readFileSync(CIRODOWN_JSON)));
  }
  if (publish) {
    // GitHub pages target is the only one for now.
    html_x_extension = false;
  } else {
    html_x_extension = commander.htmlXExtension;
  }
  let options = {
    body_only: commander.bodyOnly,
    cirodown_json: cirodown_json,
    html_embed: commander.htmlEmbed,
    html_x_extension: html_x_extension,
    html_single_page: commander.htmlSinglePage,
    output_format: commander.outputFormat,
    read_include: function(input_path) {
      return fs.readFileSync(input_path + CIRODOWN_EXT, ENCODING);
    },
    render: true,
    show_ast: commander.showAstInside,
    show_parse: commander.showParse,
    show_tokens: commander.showTokensInside,
    show_tokenize: commander.showTokenize,
    template_vars: {},
    xss_unsafe: commander.xssUnsafe,
  };
  if (commander.template !== undefined) {
    options.template = fs.readFileSync(commander.template).toString();
  } else if ('template' in cirodown_json) {
    options.template = fs.readFileSync(cirodown_json.template).toString();
  } else {
    options.template = undefined;
  }
  let input_path_is_file;
  if (inputPath === undefined) {
    input_dir = undefined;
    input_path_is_file = false;
  } else {
    input_path_is_file = fs.lstatSync(inputPath).isFile();
    if (input_path_is_file) {
      input_dir = path.dirname(inputPath);
    } else {
      input_dir = inputPath;
    }
    try {
      options.template_vars.git_sha = git_sha(input_dir);
    } catch(error) {
      // Not in a git repo.
    }
  }
  let outdir;
  if (commander.outdir === undefined) {
    outdir = '.';
  } else {
    outdir = commander.outdir;
  }
  if (commander.generate || commander.generateMultifile) {
    fs.mkdirSync(outdir, {recursive: true});

    // Generate package.json.
    const package_json = JSON.parse(fs.readFileSync(cirodown_nodejs.PACKAGE_PACKAGE_JSON_PATH).toString());
    const package_json_str = `{
  "dependencies": {
    "cirodown": "${package_json.version}"
  }
}
`;
    fs.writeFileSync(path.join(outdir, 'package.json'), package_json_str);

    const new_cirodown_json = {};

    // Generate .gitignore. Reuse our gitignore up to the first blank line.
    let gitignore_new = '';
    const gitignore = fs.readFileSync(cirodown_nodejs.GITIGNORE_PATH, ENCODING);
    for (const line of gitignore.split('\n')) {
      if (line === '') {
        break;
      }
      gitignore_new += line + '\n';
    }
    fs.writeFileSync(path.join(outdir, '.gitignore'), gitignore_new);

    // Generate README.ciro and other .ciro files.
    let readme_cirodown_str = `= Cirodown hello world

Hello!
`;
    if (commander.generateMultifile) {
      readme_cirodown_str += `
\\Toc

== And now an include

\\Include[not-readme]
`
      not_readme_str = `= Not the readme

A link to another file: \\x[and-now-an-include]
`
      fs.writeFileSync(path.join(outdir, 'not-readme.ciro'), not_readme_str);
    }
    fs.writeFileSync(path.join(outdir, 'README.ciro'), readme_cirodown_str);
    if (commander.generateMultifile) {
      fs.copyFileSync(path.join(cirodown_nodejs.PACKAGE_PATH, 'main.liquid.html'), path.join(outdir, 'main.liquid.html'));
      fs.copyFileSync(path.join(cirodown_nodejs.PACKAGE_PATH, 'main.scss'), path.join(outdir, 'main.scss'));
      new_cirodown_json.template = 'main.liquid.html';
    }

    if (new_cirodown_json !== {}) {
      fs.writeFileSync(path.join(outdir, CIRODOWN_JSON), JSON.stringify(new_cirodown_json, null, 2) + '\n');
    }
    process.exit(0);
  }
  let convert_input_options = {
    commander: commander,
    encoding: ENCODING,
    external_css_and_js: false,
    had_error: false,
    out_css_path: cirodown_nodejs.PACKAGE_OUT_CSS_LOCAL_PATH,
    out_js_path: cirodown_nodejs.PACKAGE_OUT_JS_LOCAL_PATH,
  };
  let outfile;
  if (commander.outfile === undefined) {
    if (
      !commander.stdout &&
      inputPath !== undefined &&
      input_path_is_file
    ) {
      input_path_parse = path.parse(inputPath);
      outfile = path.join(input_path_parse.dir,
        get_renamed_basename(input_path_parse.name) + '.' + options.output_format);
    }
  } else {
    outfile = commander.outfile;
  }
  if (outfile !== undefined) {
    convert_input_options.output_path = outfile;
  }
  if (inputPath === undefined) {
    title = 'stdin';
    input = fs.readFileSync(0, ENCODING);
    output = convert_input(input, options, convert_input_options);
  } else {
    if (!fs.existsSync(inputPath)) {
      cli_error(`input_path does not exist: "${inputPath}"`);
    }
    let tmpdir;
    let publish_dir;
    let publish_out_dir;
    let cmd_options = {
      dry_run: commander.dryRun,
      throw_on_error: true,
    }
    if (input_path_is_file) {
      input_path_is_file = true;
      tmpdir = TMP_DIRNAME;
    } else {
      input_path_is_file = false;
      tmpdir = path.join(inputPath, TMP_DIRNAME);
      if (publish) {
        publish_dir = path.join(tmpdir, 'publish');
        publish_git_dir = path.join(publish_dir, '.git');
        if (fs.existsSync(publish_git_dir)) {
          // This cleanup has to be done before the database initialization.
          cmd_get_stdout('git', ['-C', publish_dir, 'clean', '-x', '-d', '-f'], cmd_options);
        }
        tmpdir = path.join(publish_dir, TMP_DIRNAME);
        publish_out_dir = path.join(publish_dir, TMP_DIRNAME);
      }
      if (outfile !== undefined) {
        cli_error(`--outfile given but multiple output files must be generated, maybe you want --outdir?`);
      }
    }

    // Setup the ID database.
    fs.mkdirSync(tmpdir, {recursive: true});
    if (commander.db) {
      const db_path = path.join(tmpdir, 'db.sqlite3');
      const ids_table_name = 'ids';
      const includes_table_name = 'includes';
      const files_table_name = 'files';
      const db = new better_sqlite3(db_path);
      if (
        db.prepare(`SELECT name
        FROM sqlite_master
        WHERE type='table' AND name='${ids_table_name}'
        `).get() === undefined
      ) {
        db.prepare(`
          CREATE TABLE '${ids_table_name}' (
            id TEXT PRIMARY KEY,
            path TEXT,
            ast_json TEXT
          )`
        ).run();
      }
      if (
        db.prepare(`SELECT name
        FROM sqlite_master
        WHERE type='table' AND name='${includes_table_name}'
        `).get() === undefined
      ) {
        db.prepare(`
          CREATE TABLE '${includes_table_name}' (
            from_id TEXT,
            from_path TEXT,
            to_id TEXT
          )`
        ).run();
      }
      if (
        db.prepare(`SELECT name
        FROM sqlite_master
        WHERE type='table' AND name='${files_table_name}'
        `).get() === undefined
      ) {
        db.prepare(`
          CREATE TABLE '${files_table_name}' (
            path TEXT PRIMARY KEY,
            toplevel_scope_cut_length INT,
            toplevel_id TEXT
          )`
        ).run();
      }
      convert_input_options.db = db;
      convert_input_options.ids_table_name = ids_table_name;
      convert_input_options.includes_table_name = includes_table_name;
      convert_input_options.files_table_name = files_table_name;
    }
    if (commander.generateRedirects) {
      generate_redirects(convert_input_options, cirodown_json, html_x_extension, outdir);
      process.exit(0);
    }
    if (commander.watch) {
      if (publish) {
        cli_error('--publish and --watch are incompatible');
      }
      if (!input_path_is_file) {
        convert_files_in_directory_extract_ids(inputPath, options, convert_input_options);
        generate_redirects(convert_input_options, cirodown_json, html_x_extension, outdir);
      }
      let watcher = chokidar.watch(inputPath, {ignored: DEFAULT_IGNORE_BASENAMES});
      watcher.on('change', function(path) {
        convert_path_to_file(input_dir, path, options, convert_input_options);
      }).on('add', function(path) {
        convert_path_to_file(input_dir, path, options, convert_input_options);
      });
    } else {
      if (input_path_is_file) {
        if (publish) {
          cli_error('--publish must take a directory as input, not a file');
        }
        output = convert_path(path.dirname(inputPath), inputPath, options, convert_input_options);
      } else {
        let actual_input;
        let publish_branch;
        let publish_outdir;
        let remote_url;
        let src_branch;

        if (publish) {
          // Clone the source to ensure that only git tracked changes get built and published.
          if (!fs.existsSync(path.join(inputPath, '.git'))) {
            cli_error('--publish must point to the root of a git repository');
          }
          remote_url = cmd_get_stdout('git', ['-C', inputPath, 'config', '--get', 'remote.origin.url'], cmd_options).slice(0, -1);
          src_branch = cmd_get_stdout('git', ['-C', inputPath, 'rev-parse', '--abbrev-ref', 'HEAD'], cmd_options).slice(0, -1);
          if (commander.dryRun) {
            remote_url = 'git@github.com:cirosantilli/cirodown.git';
            src_branch = 'master';
          }
          const parsed_remote_url = git_url_parse(remote_url);
          if (parsed_remote_url.source !== 'github.com') {
            cli_error('only know how  to publish to origin == github.com currently, please send a patch');
          }
          let remote_url_path_components = parsed_remote_url.pathname.split(path.sep);
          if (remote_url_path_components[2].startsWith(remote_url_path_components[1] + '.github.io')) {
            publish_branch = 'master';
          } else {
            publish_branch = 'gh-pages';
          }
          if (src_branch === publish_branch) {
            cli_error(`source and publish branches are the same: ${publish_branch}`);
          }
          fs.mkdirSync(publish_dir, {recursive: true});
          if (commander.publishCommit !== undefined) {
            cmd_get_stdout('git', ['-C', inputPath, 'add', '-u'], cmd_options);
            cmd_get_stdout('git', ['-C', inputPath, 'commit', '-m', commander.publishCommit], cmd_options);
          }
          if (fs.existsSync(publish_git_dir)) {
            cmd_get_stdout('git', ['-C', publish_dir, 'checkout', '--', '.'], cmd_options);
            cmd_get_stdout('git', ['-C', publish_dir, 'pull'], cmd_options);
            cmd_get_stdout('git', ['-C', publish_dir, 'submodule', 'update', '--init'], cmd_options);
          } else {
            cmd_get_stdout('git', ['clone', '--recursive', inputPath, publish_dir], cmd_options);
          }

          // Set some variables especially for publishing.
          actual_input = publish_dir;
          publish_outdir = path.join(publish_out_dir, 'publish');
          convert_input_options.out_css_path = path.join(publish_outdir, cirodown_nodejs.PACKAGE_OUT_CSS_BASENAME);
          convert_input_options.out_js_path = path.join(publish_outdir, cirodown_nodejs.PACKAGE_OUT_JS_BASENAME);
          convert_input_options.external_css_and_js = true;
          // Remove all files from the gh-pages repository in case some were removed from the original source.
          if (fs.existsSync(path.join(publish_out_dir, '.git'))) {
            cmd_get_stdout('git', ['-C', publish_outdir, 'rm', '-r', '-f', '.'], cmd_options);
          }
        } else {
          actual_input = inputPath;
          publish_outdir = outdir;
        }
        convert_input_options.outdir = publish_outdir;

        // Do the actual conversion.
        convert_files_in_directory_extract_ids(actual_input, options, convert_input_options);
        convert_files_in_directory(actual_input, options, convert_input_options);
        generate_redirects(convert_input_options, cirodown_json, html_x_extension, publish_outdir);

        // Publish the converted output if build succeeded.
        if (publish && !convert_input_options.had_error) {
          // Push the original source.
          cmd_get_stdout('git', ['-C', inputPath, 'push'], cmd_options);
          cmd_get_stdout('git', ['-C', publish_outdir, 'init'], cmd_options);
          // https://stackoverflow.com/questions/42871542/how-to-create-a-git-repository-with-the-default-branch-name-other-than-master
          cmd_get_stdout('git', ['-C', publish_outdir, 'checkout', '-B', publish_branch], cmd_options);
          try {
            // Fails if remote already exists.
            cmd_get_stdout('git', ['-C', publish_outdir, 'remote', 'add', 'origin', remote_url], cmd_options);
          } catch(error) {
            cmd_get_stdout('git', ['-C', publish_outdir, 'remote', 'set-url', 'origin', remote_url], cmd_options);
          }
          // Ensure that we are up-to-date with the upstream gh-pages if one exists.
          // TODO may fail on initial one, do a check for that.
          cmd_get_stdout('git', ['-C', publish_outdir, 'fetch', 'origin'], cmd_options);
          cmd_get_stdout('git', ['-C', publish_outdir, 'reset', `origin/${publish_branch}`], cmd_options);

          // Generate special files needed for GitHub pages.
          gemfile_content = "gem 'github-pages', group: :jekyll_plugins\n";
          fs.writeFileSync(path.join(publish_outdir, 'Gemfile'), gemfile_content);

          // Commit and push.
          if ('prepublish' in cirodown_json) {
            const prepublish_path = cirodown_json.prepublish
            if (!fs.existsSync(prepublish_path)) {
              cli_error(`${CIRODOWN_JSON} prepublish file not found: ${prepublish_path}`);
            }
            try {
              cmd_get_stdout(path.resolve(prepublish_path), [publish_outdir]);
            } catch(error) {
              cli_error(`${CIRODOWN_JSON} prepublish command exited non-zero, aborting`);
            }
          }
          // Copy the CSS into the repository.
          fs.copyFileSync(cirodown_nodejs.PACKAGE_OUT_CSS_PATH, convert_input_options.out_css_path);
          fs.copyFileSync(cirodown_nodejs.PACKAGE_OUT_JS_LOCAL_PATH, convert_input_options.out_js_path);
          cmd_get_stdout('git', ['-C', publish_outdir, 'add', '.'], cmd_options);
          source_commit = git_sha(inputPath, src_branch);
          cmd_get_stdout('git', ['-C', publish_outdir, 'commit', '-m', source_commit], cmd_options);
          cmd_get_stdout('git', ['-C', publish_outdir, 'push', 'origin', `${publish_branch}:${publish_branch}`], cmd_options);
        }
      }
    }
  }
  if (output !== undefined) {
    if (outfile === undefined) {
      process.stdout.write(output);
    } else {
      fs.writeFileSync(outfile, output);
    }
  }
  if (!commander.watch) {
    process.exit(convert_input_options.had_error);
  }
}
