#!/usr/bin/env node

// https://cirosantilli.com/cirodown#generate-paragraphs

const cli_args = process.argv.slice(2);

let spread;
if (cli_args.length > 0) {
  npars = parseInt(cli_args[0]);
} else {
  npars = 10;
}

for (let i = 0; i < npars; i++) {
  console.log(`${i}\n`);
}
