#!/usr/bin/env node
const fs = require('fs');
const ourbigbook_nodejs = require('./nodejs');
let v = JSON.parse(fs.readFileSync(ourbigbook_nodejs.PACKAGE_PACKAGE_JSON_PATH).toString()).version
let vs = v.split('.')
vs[vs.length - 1] = parseInt(vs[vs.length - 1], 10) + 1
console.log(vs.join('.'))
