#!/usr/bin/env bash
# https://docs.ourbigbook.com#do-the-release
set -eux
test=true
while [ $# -gt 0 ]; do
  case $1 in
    -T)
      test=false
      shift
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done
if [ $# -lt 1 ]; then
  version="$(./inc-version)"
else
  version="$1"
fi
# Although this is also run by `npm run publish`, it is also
# required for some tests to pass so we have to run it here too.
npm run build-assets
if $test; then
  npm run test-release
fi
# This also does npm run build-assets
npm run publish
sed -i "s/  \"version\":.*/  \"version\": \"${version}\",/" package.json
# To update the package-lock.json.
# Not sure why needed twice, some mess with link madness.
npm run link
npm run link

# Re-release vscode extension to use the updated ourbigbook package.
sed -i "s/  \"ourbigbook\":.*/  \"ourbigbook\": \"${version}\",/" vscode/package.json
ext_version="$(./inc-version vscode/package.json)"
sed -i "s/  \"version\":.*/  \"version\": \"${ext_version}\",/" vscode/package.json

git add -u
git commit -m "version $version"
git tag -m "$version" "$version"
git push --follow-tags
npm publish

# vscode extension
vsce package
vsce publish

./update-templates
