#!/usr/bin/env bash
set -eux
commit=false
while [ $# -gt 0 ]; do
  case $1 in
    --commit)
      commit=true
      shift
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      break
      ;;
  esac
done
if [ $# -gt 0 ]; then
  version="$1"
  sed -i "s/  \"ourbigbook\":[^,]*/  \"ourbigbook\": \"${version}\"/" vscode/package.json
fi
ext_version="$(./inc-version vscode/package.json)"
sed -i "s/  \"version\":[^,]*/  \"version\": \"${ext_version}\"/" vscode/package.json
if $commit; then
  git add vscode/package.json vscode/package-lock.json
  git commit -m "vscode: version $ext_version"
  git tag -m "vscode-$ext_version" "vscode-$ext_version"
  git push --follow-tags
fi
