#!/usr/bin/env bash

set -eux

template_repos_dir=template/repos

update-template() (
  name="$1"
  dirname="$2"
  dir="${template_repos_dir}/$dirname"
  rm -rf "$dir"
  cirodown --generate="$name" --outdir="$dir"
  cd "$dir"
  npm install
  git init
  git add .
  git commit -m 'Create template'
  git remote add origin "git@github.com:cirosantilli/${dirname}.git"
  git push -f
  npx cirodown --publish
)

update-template min "cirodown-template-min"
update-template default "cirodown-template"
