#!/usr/bin/env bash

set -eux

curl https://api.openai.com/v1/batches?limit=20 \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -H "Content-Type: application/json" |
jq -r '.data[] | "\(.id) \(.status) (\(.request_counts.completed)/\(.request_counts.total))"'
